### PR TITLE
Fixes for va_forms transformer

### LINKED ISSUE #14611: Missing href values on Find Forms pages
## Description
Find Forms pages are missing `href` values in two links.

## Example
```
build/localhost/find-forms/about-form-10-1313-4/index.html
1378:          <a href target="_blank" download data-widget-type="find-va-forms-invalid-pdf-alert" data-form-number="10-1313-4">
1385:          <a href class="usa-button-primary va-button-primary" id="0d7dd160e750369db449614e35ff85b0">
```

## Tasks
- [ ] Figure out why there are missing `href`s.
- [ ] Resolve issue, and verify the output matches the GraphQL content build.

### PR DESCRIPTION
**Pull request by U-DON**
## Description
Various fixes for Find Forms pages to reach parity in content.

Started with a fix for the missing `href` values to resolve department-of-veterans-affairs/va.gov-team#14611, but went ahead and fixed all the other issues as well.

## Testing done
Diffed some Find Forms pages between builds. Validated affected transformers.

## Acceptance criteria
- [ ] Find Form pages should have the same content between the CMS export and GraphQL builds.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

File: src/site/stages/build/process-cms-exports/transformers/node-va_form.js [hunk 1]
```diff
@@ -1,46 +1,52 @@
...
+          fieldVaFormNumber: e.fieldVaFormNumber,
+          fieldVaFormUsage: e.fieldVaFormUsage,
+          fieldVaFormUrl: e.fieldVaFormUrl,
+        }
+      : {
+          fieldVaFormName: getDrupalValue(e.field_va_form_name),
+          fieldVaFormNumber: getDrupalValue(e.field_va_form_number),
+          fieldVaFormUsage: e.field_va_form_usage[0] || null,
+          fieldVaFormUrl: e.field_va_form_url[0] || null,
+        },
```
Comment (U-DON) [inline src/site/stages/build/process-cms-exports/transformers/node-va_form.js:41]: https://github.com/department-of-veterans-affairs/vets-website/blob/4c17d79357f4968eae0a2a0f97f15106d6e1e97b/src/site/layouts/va_form.drupal.liquid#L118-L122

**Review by jhonny218 — APPROVED** [review]
