### PR TITLE
SSO Announcement Modal fixes: overflow/scroll styling + content updates

### LINKED ISSUE #7813: [ZOOM]: SSOe Comms Modal: Headline unreadable at 200% and 250% zoom
## What happened?
Per VSP accessibility [zoom tests](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_id=21&group_order=asc) I tested the SSOe comms modal when Chrome was at 1280px width. 

- The modal was readable at 400% and 300% zoom (the top of the modal locked to the top of the screen and there was no overflow on L or R sides).
- The headline was partially cut off at 200% and fully 250% zoom and I could not scroll up to access the headline. 

## Specs:
- Device: MacBook
- Browser: Chrome, 1280px width

## Steps to Reproduce
1. Sign in on staging.va.gov with account for the first time to see modal
2. Set browser width to 1280px
3. Zoom into 200% 

## Desired behavior
Modal at 200% and 250% should lock to top of the screen as it does at 300% and 400%.

### PR DESCRIPTION
**Pull request by hinzed1127**
## Description
closes department-of-veterans-affairs/va.gov-team#7813

When zoom sizes increase the announcement modal to a height larger than the viewport, it cuts off the headline. This fix makes sure the top of the viewport is showing the top of the modal, and any overflow is still scroll-able.

## Testing done
Manual verification w/ various zoom settings

## Screenshots

Example of one of the problem settings (250% zoom, width > 1200px), now fixed
Screen Shot 2020-05-19 at 7 07 38 PM

## Acceptance criteria
- [x] Entire announcement modal is visible and/or scroll-able, regardless of browser's zoom percentage

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ericbuckley — APPROVED** [review]

File: src/platform/site-wide/announcements/components/SingleSignOnInfoModal.jsx [hunk 1]
```diff
@@ -14,8 +14,8 @@ export default function SingleSignOnInfoModal({
         Sign in once to access the VA sites you use most
       </h1>
       <p>
-        Now when you sign into VA.gov, we’ll also sign you into MyHealtheVet,
-        eBenefits, and other VA sites.
+        Now when you sign into VA.gov, we’ll also sign you into MyHealtheVet and
+        other VA sites.
```
Comment (hinzed1127) [inline src/platform/site-wide/announcements/components/SingleSignOnInfoModal.jsx:18]: small content update that's needed as part of SSO launch

**Review by U-DON — APPROVED** [review]

**Comment by U-DON** [comment]
Have you considered using the [utility class](https://design.va.gov/utilities/height-and-width#max-height) `.vads-u-max-height--viewport`?

**Comment by hinzed1127** [comment]
@U-DON unfortunately the styling issue is on the modal component specifically and not solved by adding the utility class to the individual component. This might be worth following up on and adding directly to the formation component, since it's the `modal-inner-content` that needs this to be applied to
