### PR TITLE
Autologin / Autologout fixes

### LINKED ISSUE #8580: Auto-login redirect loop
**Expected Behavior**

Logging in with IAM enabled results in a user with an active SSO session upon redirection back to VA.gov

**Actual Behavior**

The keep-alive call and subsequent `hasSessionSSO` flag is failing, causing a successful login to immediately be redirected to an auto-logout

### PR DESCRIPTION
**Pull request by ericbuckley**
This takes all of the logic for inbound SSO (i.e., triggering auto login or logout based on a person's SSOe session status) and encapsulates in a container component. It remains in the user-nav to be paired with vets-api session logic, as well as the need for it to be rendered site-wide on each page load.

closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/8580

### CODE REVIEW

File: src/platform/utilities/sso/keepAliveSSO.js [hunk 1]
```diff
@@ -1,12 +1,28 @@
...
+      cache: 'no-store',
+      headers: {
+        'Content-Type': 'application/json',
+      },
+    });
+    return resp.headers.get('session-timeout');
+  } catch (err) {
+    Sentry.withScope(scope => {
+      scope.setExtra('error', err);
+      Sentry.captureMessage(`SSOe error: ${err.message}`);
```
[the remark this answers is not in the document]
Comment (bkjohnson) [reply src/platform/utilities/sso/keepAliveSSO.js:24]: This is fine.

**Comment by hinzed1127** [comment]
we can use the interval inbound logic checks down if we subsequently decide to go that route, but for now LGTM

**Review by hinzed1127 — APPROVED** [review]
we can use the interval inbound logic checks down if we subsequently decide to go that route, but for now LGTM

File: src/platform/site-wide/user-nav/containers/AutoSSO.jsx [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+    const { hasCalledKeepAlive } = this.state;
+
+    if (useSSOe && useInboundSSOe && !hasCalledKeepAlive) {
+      this.checkStatus();
+    }
+  }
+
+  checkStatus = () => {
+    ssoKeepAliveSession().then(() => {
+      if (hasSession() && hasSessionSSO() === 'false') {
```
Comment (ncksllvn) [inline src/platform/site-wide/user-nav/containers/AutoSSO.jsx:25]: So that you don't have to work with the stringified versions, I would use `JSON.parse` inside of `hasSessionSSO`. `JSON.parse(sessionStorage.get('someBoolean')) => boolean`. That way you could just use `hasSessionSSO() => boolean`. You could also use `async` and `await` here -

```js
checkStatus = async () => {
   await ssoKeepAliveSession();
   // ...
}
```

File: src/platform/site-wide/user-nav/containers/AutoSSO.jsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+        autoLogout();
+      } else if (!hasSession() && hasSessionSSO() === 'true') {
+        autoLogin();
+      }
+
+      this.setState({ hasCalledKeepAlive: true });
```
Comment (ncksllvn) [inline src/platform/site-wide/user-nav/containers/AutoSSO.jsx:31]: Don't know how, but `hasCalledKeepAlive` seems like it could be stored or derived out of Redux, like added into state after the call to `autoLogin` or `autoLogout`

These conditions cover "true && false" and "false && true" but should there be an `else` or anything? If both are false or both true

File: src/platform/utilities/sso/index.js [hunk 4]
```diff
@@ -1,50 +1,36 @@
...
-    Sentry.withScope(scope => {
-      scope.setExtra('error', err);
-      Sentry.captureMessage(`SSOe error: ${err.message}`);
-    });
+  const ttl = await keepAlive();
+  if (ttl > 0) {
+    // ttl is positive, user has an active session
+    const expirationTime = new Date();
+    // 'ttl' is in seconds, convert to milliseconds
+    expirationTime.setTime(expirationTime.getTime() + ttl * 1000);
```
Comment (ncksllvn) [inline src/platform/utilities/sso/index.js:16]: I think I commented this before so feel free to ignore, but I try not to do any arithmetic with plain JS Dates bc of browser quirkiness

**Review by ncksllvn — APPROVED** [review]

File: src/platform/site-wide/user-nav/containers/AutoSSO.jsx (hunk 3 above)
Comment (hinzed1127) [reply src/platform/site-wide/user-nav/containers/AutoSSO.jsx:31]: Those conditions are both inherently covered already:

* both true = already logged in across sessions, do nothing
* both false = no sessions active, do nothing.

Comment (hinzed1127) [reply src/platform/site-wide/user-nav/containers/AutoSSO.jsx:31]: the redux point is interesting. would that be something added to `user.login` or something like that?

File: src/platform/utilities/sso/index.js (hunk 4 above)
Comment (hinzed1127) [reply src/platform/utilities/sso/index.js:17]: converted to moment after clearing up performance concerns 👍

File: src/platform/site-wide/user-nav/containers/AutoSSO.jsx (hunk 3 above)
Comment (ncksllvn) [reply src/platform/site-wide/user-nav/containers/AutoSSO.jsx]: Yeah, if these utilities can be dispatched as actions, I'd look at adding an `sso` reducer or something like that to this reducer - `src/platform/user/authentication/reducers/index.js`

Comment (hinzed1127) [reply src/platform/site-wide/user-nav/containers/AutoSSO.jsx]: been a bit since I've touched the whole of a redux flow, but I made that refactor 😅

File: src/platform/site-wide/user-nav/containers/AutoSSO.jsx [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+  }
+
+  toggleKeepAlive();
+}
+
+function AutoSSO(props) {
+  const { useSSOe, useInboundSSOe, hasCalledKeepAlive } = props;
+
+  if (
+    useSSOe &&
```
Comment (ncksllvn) [inline src/platform/site-wide/user-nav/containers/AutoSSO.jsx:29]: Just brainstorming, but `useSSOe` could possibly return false each time if `environment.isLocalhost()`

**Review by ncksllvn — APPROVED** [review]
This is awesome work!! Love seeing the data make its way into Redux 🚀 Well done!

File: src/platform/site-wide/user-nav/containers/AutoSSO.jsx (hunk 5 above)
Comment (hinzed1127) [reply src/platform/site-wide/user-nav/containers/AutoSSO.jsx]: that's a good point. we want that to happen every time, so might as well put it in the selector.

note: it's `useInboundSSOe` we want that condition for. `useSSOe` is fine for localhost

**Review by patrickvinograd — COMMENTED** [review]
I  don't feel qualified to leave a 👍 but purely from an encapsulation perspective this looks a lot cleaner.

**Review by rianfowler — APPROVED** [review]
