### PR TITLE
93403 Update toxic exposure date validations and review page error messages

### LINKED ISSUE #93403: Toxic Exposure - (found during 25%) - invalid date XXXX is coming through for the year in exposure dates fields
### Description
As a Veteran, when I enter a year date in an optional field on my 526 form, I expect that it will be sent to VA and my claim will be submitted successfully. This impacted 8 submissions for 3 unique users. The form component doesn't provide four-digit year validation and doesn't allow a Veteran to complete only one field (either date, month, or year). We've talked with the forms team and are not sure if or when a fix is forthcoming. Because these fail completely and want to avoid this, we are considering a different approach.

### Issue 1 - "Invalid Date"
Today, a Veteran's 526 submission fails the primary and backup path when they don't enter a year (although the date fields are optional) because "XXXX-12 is not a valid date.". This is has currently affected 7 submissions for 2 unique Veterans. 

{"errors":[{"detail":"XXXX-12 is not a valid date.","source":"data/attributes//toxicExposure/multipleExposures//exposureDates/beginDate","title":"Unprocessable Entity","status":"422"}

#### Tasks
- [ ] Ask LH if they can relax the validation rules for this scenario
- [ ] We could consider overriding the [web component pattern](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/datePatterns.jsx#L326)

---
### Issue 2 - "Two-digit Year"
Today, a Veteran's 526 submission fails the primary and backup path when they enter a two-digit year (although the date fields are optional) because the year is two digits, and "0" isn't a valid choice for month or day. This is has currently affected 1 submission, for 1 unique Veteran.

Another issue is this is coming through from the frontend: `"endDate": "77-06-01"` (originally seen in the `otherHerbicideLocations` attribute), which the backend parsed as `"endDate": "77-0--0"`, which lighthouse no likey

#### Tasks
- [ ] Ask LH if they can relax the validation rules for this scenario
- [ ] We could consider overriding the [web component pattern](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/datePatterns.jsx#L326)
- [ ] Explore what the Veteran-facing experience is like when we set the backend schema as well and identify if there's an option to send an error message back to the frontend and what this would look like.

### Additional Information
- We're having trouble reproducing both of these issues
- How did EVSS handle this
- Can we/should we update/change the schema

### PR DESCRIPTION
**Pull request by christinec-fftc**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

###  TeamSites 
Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
- Update FE schema used for toxic exposure dates to no longer allow X's in years which were causing submission failures
- Error message improvements on the review page
- More unit tests to check for valid and invalid date submission
- Dependent on vets-json-schema change
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/939

team: @department-of-veterans-affairs/dbex-trex 

## Related issue(s)
- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#93403

## Testing done
- Unit tests updated and lots of manual testing

**Manual test setup**
1. Enable toggle `disability_526_toxic_exposure`
2. Start a new claim with new conditions
3. On the toxic-exposure/conditions page, select at least one new condition
4. For each of the TE locations or hazards questions, select at least one hazard or question
5. **regression:** enter full dates (month, day, year) on a TE details page. **verify**: date(s) are saved and claim can be submitted
6. **new:** enter month + day + partial year on a TE details page.  **verify** error message displays on the page "Please enter a valid current or past date" or "Please enter a year between 1900 and 2124", depending on what was entered.
7. **new:** for step 6, if somehow you are able to get the date saved and move forward (known issue with the component), continue all the way to the review page and try to submit. **verify** new error message displays on the review page (as shown in screenshot)

## Screenshots
Both screenshots were built with the same formData. Invalid or empty dates were used for the years and invalid chars (e.g. `(` or `?`) were used for the other locations and hazards fields. Note how we are doing more validations here for the year, so more error messages display on the review page. We also added friendly error messages for parsing issues on the pages with other herbicide locations and other exposures fields.

Each of the links goes to the tops of the Conditions section and the page itself should be expanded within it in edit mode. 
[93403 review errors pr.pdf](https://github.com/user-attachments/files/17234482/93403.review.errors.pr.pdf)

## What areas of the site does it impact?
526ez

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [n/a] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [n/a] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback
none

### CODE REVIEW

File: src/applications/disability-benefits/all-claims/constants.js [hunk 1]
```diff
@@ -403,3 +403,14 @@ export const ADDITIONAL_EXPOSURES = Object.freeze({
...
+
+/* Toxic exposure date must be in the format of YYYY-MM-DD with the following
+      year: must be 4 digits and start with 19 or 20, e.g. 1990 or 2000
+      month: must be 2 digits, ranging from 01 - 12
+      day: must be 2 digits, ranging from 01 - 31
+   Note: X's are being removed to avoid submission failures   
+*/
+export const toxicExposureDate = {
+  pattern: '^(?:19|20)[0-9][0-9]-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$',
+  type: 'string',
```
Comment (christinec-fftc) [inline src/applications/disability-benefits/all-claims/constants.js:415]: fyi the current regex allow's X's in each of the fields
`"^(\\d{4}|XXXX)-(0[1-9]|1[0-2]|XX)-(0[1-9]|[1-2][0-9]|3[0-1]|XX)$"`

**Review by tommasina-va — APPROVED** [review]
Amazing work on this!

**Review by sethdarragile6 — APPROVED** [review]

**Review by CBonade — APPROVED** [review]
