### PR TITLE
Fixes defect with Material Type Filter not working

### LINKED ISSUE #11445: Material type filter screening
## Describe the defect

On [Outreach Materials](https://www.va.gov/outreach-and-events/outreach-materials/) three PACT Act PDFs are not showing up when the "Poster, Flyer, brochure and fact sheets" filter is selected.

## To Reproduce
1. Go to Outreach Materials
2. Click through pages to find PACT Scams PDF (probably on last (9th) page of results)
3. Select filter for Posters etc
4. See that PACT Scams PDF (and other PACT ones) are not among the 3 pages of results

## Screenshots

Present on unfiltered view:

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by jtmst**
## Description
closes department-of-veterans-affairs/va.gov-cms/issues/11445
Paginator was not correctly showing pages at the end of the page list, resulting in PACT act and other documents not being visible

Several bugs around the Outreach material page paginator were noticed while working on this, but those are to be addressed in a follow up ticket

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11445

## Testing done
local visual testing
Steps to QA:
- navigate to http://localhost:3002/outreach-and-events/outreach-materials/
- set file type filter to poster
- observe that there are 4 pages, including the PACT act documents on the final page

## Screenshots
Screen Shot 2022-11-09 at 9 27 17 AM
Screen Shot 2022-11-09 at 9 27 36 AM

## Acceptance criteria
- [ ] PACT act documentation is visible under the correct file type filters

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by it-harrison — APPROVED** [review]

**Comment by jilladams** [comment]
(gotcha with the `closes #xxxx` thing = it only works exactly that was in CMS repo. In vw / cb, gotta do the issue path. Updated in body -- I think it'll work this way. We'll see when it merges!)

**Review by jilladams — APPROVED** [review]
QA review (not merge-unblocking):
* http://88287d7768946cd52a4c1eaee6e7ea86.review.vetsgov-internal/outreach-and-events/outreach-materials/
* PACT info shows correctly when filtering by Posters

One Q: we need front-end review here and vsa frontend group wasn't tagged automagically. Should Ryan / Bryan get added as reviewers?

File: src/applications/public-outreach-materials/libraries/library-filters.js [hunk 1]
```diff
@@ -102,30 +102,31 @@ export function libraryCurrent() {
...
   if (document.getElementById('pager-nums-insert')) {
     const diff = pages - activePage;
     let pagerHtml;
     // This is our active page / pager button.
     pagerHtml = `<a href="#${activePage}" aria-label="Page ${activePage}" aria-current="true" id="va-pagination-active-num" class="va-pagination-active a-page-numbers pager-focus-item">
     ${activePage}</a>`;
-    // If we have more than one page, add a button in front of active button.
-    if (diff > 1 && (numCards.first === undefined || numCards.first > 9)) {
+    // If we have more than one page, add a button in front of active button
+    if (diff >= 1 && (numCards.first === undefined || numCards.last > 9)) {
```
Comment (ryguyk) [inline src/applications/public-outreach-materials/libraries/library-filters.js:115]: Why are we checking `numCards.last > 9`? Does the number of cards on a page matter if the number of pages has already been calculated?

Comment (ryguyk) [reply src/applications/public-outreach-materials/libraries/library-filters.js:115]: Additionally, why keep the check for `numCards.first === undefined`? It seems pretty clear that this was initially added to accommodate the attempt to check an integer for a property (so it's always undefined). Now that `numCards` is correctly initialized to an object with properties `first` and `last`, would it ever be undefined? And, even if it would be, why would that affect the rendering of the pager?

**Review by ryguyk — COMMENTED** [review]
This code leaves me with a lot of questions, though almost all of those questions come from preexisting code. Still, I'm not sure we should leave things as is if we are already in here touching it. I can certainly understand that some of the bugs and odd behavior should be captured in a separate ticket.

File: src/applications/public-outreach-materials/libraries/library-filters.js (hunk 1 above)
Comment (jtmst) [reply src/applications/public-outreach-materials/libraries/library-filters.js]: removed the extra conditionals

Comment (jilladams) [reply src/applications/public-outreach-materials/libraries/library-filters.js]: @ryguyk thoughts on next steps (approval vs. new feedback)?  Keeping my eye on this PR as it's a sprint goal.

**Review by ryguyk — APPROVED** [review]
This seems much better to me. Thanks for fixing.
