### PR TITLE
[#128464] - Fix back button on choose-expense goes back to the correct page

### LINKED ISSUE #128464: Going back (bottom-left on-screen button) from ‘choose expense’ page goes back to the correct page.
## Purpose
The back button on the choose-expense page should take you back to either the Review or Intro page depending on which one you came from.

### Reproduce:
1. Go to claim status list
2. Go to claim details
3. Click continue claim
4. `<should be on review page>`
5. Click "Add another expense"
6. Click the bottom-left on-screen `Back` button
7. `<goes to complex claims intro screen>`
8. `<does not redirect>`

### Expected behavior:
1. Go to claim status list
2. Go to claim details
3. Click continue claim
4. `<should be on review page>`
5. Click "Add another expense"
6. Click the top bottom-left on-screen `Back` button
7. Goes to review page

### Notes
Image

### PR DESCRIPTION
**Pull request by scohen-theta**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Fixed how the back button on the choose-expense page was behaving, so that it takes you back to either the complex claims `intro` or `review` page depending on how you arrived.

Redux is now used to track how you've arrived to the choose-expense page, for the cases where we care (coming from the Intro page or the Review page). This lets us know how to navigate back even during the multi-page operation of adding a new expense.

Note this is not related to the Back link at the top. This is the secondary button at the bottom of the page.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/128464

## Screenshots
image

## What areas of the site does it impact?
Travel Pay - Complex Claims

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

File: src/applications/travel-pay/redux/reducer.js [hunk 1]
```diff
@@ -164,6 +156,7 @@ const initialState = {
 };
 
 function travelPayReducer(state = initialState, action) {
+  /* eslint-disable sonarjs/max-switch-cases */
```
Comment (scohen-theta) [inline src/applications/travel-pay/redux/reducer.js]: Finally pushed it over the edge! Let me know if this is OK.

Comment (seesleestak) [inline src/applications/travel-pay/redux/reducer.js]: I'm not seeing this lint error locally when removing this lint disable. Is this something you get lint errors for?

File: src/applications/travel-pay/redux/reducer.js [hunk 2]
```diff
@@ -709,6 +620,12 @@ function travelPayReducer(state = initialState, action) {
         reviewPageAlert: null,
       };
 
+    case SET_EXPENSE_BACK_DESTINATION:
+      return {
+        ...state,
+        expenseBackDestination: action.payload,
+      };
```
Comment (seesleestak) [inline src/applications/travel-pay/redux/reducer.js]: Can we add this within the `complexClaim` namespace in the store since it's specific to the complex claims flow?

File: src/applications/travel-pay/components/complex-claims/pages/ReviewPage.jsx [hunk 3]
```diff
@@ -71,7 +71,9 @@ const ReviewPage = () => {
   };
 
   const addMoreExpenses = () => {
-    navigate(`/file-new-claim/${apptId}/${claimId}/choose-expense`);
+    navigate(`/file-new-claim/${apptId}/${claimId}/choose-expense`, {
+      state: { backDestination: 'review' },
+    });
```
[the remark this answers is not in the document]
Comment (scohen-theta) [reply src/applications/travel-pay/components/complex-claims/pages/ReviewPage.jsx]: We could remove the navigation state and instead call `dispatch(setExpenseBackDestination("intro"))` or `dispatch(setExpenseBackDestination("review"))` right before we do the navigate call on the intro and review pages.  I think then we could also remove the useEffect since the state is already set.

I opted for this approach just to keep the redux action isolated in one spot. But removing the location would reduce the amount of code for sure and make things a bit simpler.

Let me know if I misunderstood your suggestion though!

[the remark this answers is not in the document]
Comment (scohen-theta) [reply src/applications/travel-pay/components/complex-claims/pages/ReviewPage.jsx]: Sounds good!

**Review by seesleestak — APPROVED** [review]
Looking good!
