### PR TITLE
Report Pact test failures

### LINKED ISSUE #14641: Report errors for failed Pact tests
Failed Pact tests aren't causing the build to fail. This caused a misunderstanding where a pact wasn't published even though the build was successful.

### PR DESCRIPTION
**Pull request by U-DON**
## Description
Previously, failed Pact tests would report success due to the following reasons:
- They ran as unit tests without the coverage option.
- The non-coverage path of the unit test script (as in just running `mocha`) suppressed error exit codes.

This fix exposes the error code from the unit test script so that it exits as a failure instead of success. Fixes department-of-veterans-affairs/va.gov-team#14641.

Also made a change to have the Pact tests output the JUnit test results for Circle to report them in the test results tab.

## Testing done
Forced a contract test failure to confirm that it would report a failure in the Circle build.

## Acceptance criteria
- [ ] Pact test failures should also result in a build failure.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

File: script/run-unit-test.js [hunk 1]
```diff
@@ -33,23 +36,23 @@ if (
...
   'src/platform/testing/unit/mocha.opts src/platform/testing/unit/helper.js';
 
-// Otherwise, run the command
 runCommand(
   `LOG_LEVEL=${options[
     'log-level'
   ].toLowerCase()} ${testRunner} --max-old-space-size=4096 --opts ${mochaOpts} --recursive ${options.path
     .map(p => `'${p}'`)
     .join(' ')}`,
-  options.coverage ? null : 0,
```
Comment (U-DON) [inline script/run-unit-test.js:54]: @jbalboni: Since you wrote this originally, I want to make sure this isn't going to break some expected behavior. I wasn't sure why the error status should be suppressed when just running `mocha` without the coverage report.

**Review by billfienberg — APPROVED** [review]
These changes make sense (unless Jeff B. indicates that `options.coverage ? null : 0,` is necessary). Nice job figuring out why the failures were being treated like successes.

File: script/run-unit-test.js (hunk 1 above)
Comment (jbalboni) [reply script/run-unit-test.js:54]: I think I did that because initially we were just running `--coverage` locally and not in CI, and it was not helpful to show the failure output when running coverage reports locally. I wouldn't expect this to break anything

**Review by jbalboni — APPROVED** [review]
