### PR TITLE
confirm address page use default profile address validation view

### LINKED ISSUE #96346: [a11y-defect-2]: Edit Benefit Letters update address buttons must be contextual for assistive technology users
### Point of contact

Trevor Pierce

### Severity level

2, Serious. Should be fixed in 1-2 sprints post-launch.

### Details

When Benefit Letter users update their address, we have a secondary routine that asks users to confirm their address. They can either use the address as entered or use the USPS recommended address. In this routine, the primary action button says "Use this address" but non-sighted users have no context what "this" means in this case. It could lead to a situation where errors are introduced or addresses incorrectly updated. Screenshot attached.

---
Image

### Reproduction steps

1. Log into https://staging.va.gov/records/download-va-letters/letters/confirm-address with a test user who has benefit letters. I used 54.
1. Turn on a screen reader of your choosing
1. Click the "Edit" button to switch the mailing address to the inline form
2. Edit or change one or two fields in the form
3. Press the "Save" button
4. Verify the updated alert box announces itself to your screen reader
5. Tab to the Use this address button and consider how important it is to know if you're using the suggested or as entered address

### Proposed solution or next steps

The button text should be more descriptive and should be contextual to which radio button users have selected. That way they have a chance to know what address is being used and double check as they feel necessary.

### References, articles, or WCAG support

1. Understanding [SC 1.3.1](https://w3.org/TR/WCAG22#info-and-relationships): Info and Relationships (Level A)
2. Understanding [SC 3.3.4](https://w3.org/TR/WCAG22#error-prevention-legal-financial-data): Error Prevention (Legal, Financial, Data) (Level AA)

### Type of issue

- [ ] Axe-core
- [x] Screenreader | assistive tech & device support
- [ ] Keyboard
- [ ] Zoom
- [ ] Color, typography, & visual elements
- [ ] Components and pattern standards
- [ ] Content organization
- [ ] Focus
- [ ] Headings
- [ ] Content style guide
- [x] Link and button labels
- [ ] Semantic HTML
- [ ] Markup and metadata
- [ ] Non-text content and media
- [ ] Overall user experience
- [x] Cognitive | user flows & navigating
- [ ] URL standards
- [ ] Something else

### PR DESCRIPTION
**Pull request by janechodance**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

After discussion with Profile team, we are going to use default address validation flow to promote consistency. Will address accessibility issues and styling with default flow in other tickets.
This code change is to condition render the description on edit address screen and remove the custom code we added before for customization.

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/96346

## Testing done

testing locally 

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |    
Screenshot 2025-03-20 at 11 35 23 AM
   |

## What areas of the site does it impact?

letter app

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

File: src/applications/letters/containers/EditAddress.jsx [hunk 1]
```diff
@@ -1,41 +1,50 @@
...
-      </va-additional-info>
+      {!showValidationView && (
+        <va-additional-info
+          id="dont-have-address"
+          class="dont-have-address"
+          trigger="If you don’t have an address"
+        >
+          <div>
+            If you don't have a mailing address you can use{' '}
+            <a href="https://faq.usps.com/s/article/What-is-General-Delivery">
```
Comment (dysbo) [inline src/applications/letters/containers/EditAddress.jsx:35]: Don't forget the `target="_blank" rel="noopener noreferrer"` bit in this link!

**Review by dysbo — APPROVED** [review]
