### PR TITLE
Passing prescription data through to ConfirmRefillModal.

### LINKED ISSUE #2948: [Rx] Fix visual regression in prescription refill modal
screen shot 2016-09-02 at 8 20 37 am

### PR DESCRIPTION
**Pull request by webinista**
- WIP on #2630 
- Closes #2948

### CODE REVIEW

File: src/js/rx/components/ConfirmRefillModal.jsx [hunk 1]
```diff
@@ -13,11 +14,11 @@ class ConfirmRefillModal extends React.Component {
     // and possibly a server request.
     event.preventDefault();
     const alertContent = (
-      <span>
-        Refill for {this.props.drug} has been requested.
-      </span>
+      <b>
```
Comment (U-DON) [inline src/js/rx/components/ConfirmRefillModal.jsx]: If alert content is generally going to be bold, I'd rather see it set in the stylesheet. Maybe for all `.rx-alert-text`. Also, just noticed the partial is still named `_va-alerts`, but can probably be renamed to `_rx-alert`.

File: src/js/rx/components/Prescription.jsx [hunk 2]
```diff
@@ -2,13 +2,30 @@ import React from 'react';
...
 class Prescription extends React.Component {
+  constructor() {
+    super();
+    this.handleSubmit = this.handleSubmit.bind(this);
+  }
+
+  handleSubmit(domEvent) {
+    domEvent.preventDefault();
+    const refillID = domEvent.target.refillID.value;
+    const content = this.props.prescriptions.items.filter((rx) => {
```
Comment (U-DON) [inline src/js/rx/components/Prescription.jsx]: Can use `Array.prototype.find` if getting only one element.

File: src/js/rx/components/Prescription.jsx [hunk 3]
```diff
@@ -2,13 +2,30 @@ import React from 'react';
...
 
 class Prescription extends React.Component {
+  constructor() {
+    super();
+    this.handleSubmit = this.handleSubmit.bind(this);
+  }
+
+  handleSubmit(domEvent) {
+    domEvent.preventDefault();
+    const refillID = domEvent.target.refillID.value;
```
Comment (U-DON) [inline src/js/rx/components/Prescription.jsx]: Nitpick: `refillId`.

File: src/js/rx/reducers/modal.js [hunk 4]
```diff
@@ -15,7 +15,7 @@ export default function modal(state = initialState, action) {
       return {
         refill: {
           visible: true,
-          content: null
+          content: action.content
```
Comment (U-DON) [inline src/js/rx/reducers/modal.js]: `content` might not be the right name for it. It makes me expect a string or DOM node. Since you're actually passing along an object of prescription attributes, maybe something like `prescription` or `rx` would be more appropriate.

File: src/js/rx/components/ConfirmRefillModal.jsx (hunk 1 above)
Comment (webinista) [inline src/js/rx/components/ConfirmRefillModal.jsx]: The point wasn't to make the text bold, it's to use a shorter tag. It's all being re-styled in CSS. `b` has about the same semantic meaning as `span`.

**Comment by U-DON** [comment]
LGTM. Will merge after tests finish.

File: src/js/rx/containers/RxRefillsApp.jsx [hunk 5]
```diff
@@ -13,10 +13,8 @@ class RxRefillsApp extends React.Component {
       <div>
         {this.props.children}
         <ConfirmRefillModal
+            {...this.props.modal.refill.content}
```
Comment (U-DON) [inline src/js/rx/containers/RxRefillsApp.jsx]: This should change to `prescription` as well.
