### PR TITLE
fix string space input bug - FL

### LINKED ISSUE #21824: Facility Locator location search field does not allow user to enter spaces
### Steps to reproduce

1. Attempt to type "fort collins" into the facility locator location search field. Note that the spaces are not allowed.

### Desired behavior

Spaces can be entered into the search field.

### PR DESCRIPTION
**Pull request by brangi**
## Description

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/21824

Reported in Slack: https://dsva.slack.com/archives/C0FQSS30V/p1616190091109200?thread_ts=1616190065.109100&cid=C0FQSS30V

### CODE REVIEW

File: src/applications/facility-locator/components/SearchControls.jsx [hunk 1]
```diff
@@ -15,7 +15,11 @@ import classNames from 'classnames';
 
 class SearchControls extends Component {
   handleQueryChange = e => {
-    this.props.onChange({ searchString: e.target.value.trim() });
+    this.props.onChange({
+      searchString: /^\s+$/.test(e.target.value)
+        ? e.target.value.trim()
+        : e.target.value,
+    });
```
Comment (mpelzsherman) [inline src/applications/facility-locator/components/SearchControls.jsx:22]: I have a simpler solution I'd like to try.

**Review by mpelzsherman — APPROVED** [review]
