### PR TITLE
fix: A11y issue s2 Headings for workflow Choice Page

### LINKED ISSUE #107726: [0781 PS] A11Y issue - Headings don’t accurately reflect structure
See: https://github.com/department-of-veterans-affairs/va.gov-team/issues/107325#issuecomment-2806871520

[3.2] 0781 choice page
Page: file-disability-claim-form-21-526ez/mental-health-form-0781/workflow

### PR DESCRIPTION
**Pull request by TranScripted**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

## Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Fix header inconsistencies in 526 `workflowChoicePage`. Previous behavior was two `h3` tags for the page title and tag. Utilizing a `hgroup` to fix the issue.

closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/107726

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/107726
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/121254 (design intake ticket - request for content to be validated and appropriate with solution approach suggested)

## Testing done
- unit test for `workflowChoicePage
- AxeTools - Accessibility
- headingsMap - ensure headings are appropriate
- ScreenReader in Safari - Accessibility
- Lighthouse in Google Chrome - Accessibility

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| `workflowChoicePage` |image|Screenshot 2026-01-05 at 10 21 37 AM|

## What areas of the site does it impact?
526 - `workflowChoicePage`

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

File: src/applications/disability-benefits/all-claims/content/form0781.jsx [hunk 1]
```diff
@@ -263,3 +263,16 @@ export function standardTitle(title) {
     </h3>
   );
 }
+
+export function customTitleWithTag(title, headingTag) {
```
Comment (LinnJS) [inline src/applications/disability-benefits/all-claims/content/form0781.jsx]: Might help clean up some of this markup?

[titleUI](https://github.com/department-of-veterans-affairs/vets-website/blob/e4b5a79ee33cbe50e17b494b56101ff9f1b3ba03/src/platform/forms-system/src/js/web-component-patterns/titlePattern.js#L123)

Not sure if its applicable for this use case.

Comment (TranScripted) [reply src/applications/disability-benefits/all-claims/content/form0781.jsx]: After discussing with @amylago, removing the custom component to stay consistent with remaining 0781 pages.

**Review by freeheeling — APPROVED** [review]
LGTM
