### PR TITLE
Fix 4328

### LINKED ISSUE #4264: The address validation modal remembers the last option you selected between opens and closes
The address validation modal remembers the last option you selected between opens and closes

To reproduce:
1. edit mailing address. use `575 20th, San Francisco CA 12345` 
2. submit the address form
3. select something other than the first recommendation (so either the user-entered address or the 2nd recommendation)
4. cancel out of the modal
5. repeat steps 1 and 2 and see that the modal defaults to selecting whichever option you'd selected in step 3

This is not expected behavior and might lead to a crash if the second time you open the modal the index of the previously selected option is out of bounds.

### LINKED ISSUE #4327: 1st attempt to force an overridable address works, 2nd+ fail
## To reproduce
1. Load the Profile: https://staging.va.gov/profile/
2. Edit the mailing address and enter an invalid address: `36319 coronado, fremont, CA 94536`
3. When prompted to confirm it's correct, force it through
4. The address will save. Yay.
5. _Without refreshing the page_ edit the address with another invalid address: `36318 coronado, fremont, CA 94536`
6. When prompted to confirm it's correct, force it through
7. This update will fail

The first update works because the FE sends the user-entered address + validation key to the update endpoint. The second fails because the FE sends the _suggestion_ from the validation API + the validation key for the _user entered_ address. Because the validation key doesn't match the address used to generate the validation key, the update fails.

### LINKED ISSUE #4328: In some cases picking a suggested address from the API will not work.
## To reproduce
1. Enter `400 65th seattle WA 12345`
2. Accept the suggested address that's selected by default and continue
3. The save will fail

This is due to the fact that that address actually returns multiple addresses from the suggestion API. We only show the user the 2nd result because that's the only CONFIRMED address. But when the user selects that address, what actually gets sent to the BE is the _first_ address that came back from the API, but that's an UNDELIVERABLE address.

## Technical details
This is the response from the validation API when you send it `400 65th seattle WA 12345`:
```json
{
  "addresses": [
    {
      "address": {
        "addressLine1": "400 N 65th St",
        "addressType": "DOMESTIC",
        "city": "Seattle",
        "countryName": "United States",
        "countryCodeIso3": "USA",
        "countyCode": "53033",
        "countyName": "King",
        "stateCode": "WA",
        "zipCode": "98103",
        "zipCodeSuffix": "5252"
      },
      "addressMetaData": {
        "confidenceScore": 100.0,
        "addressType": "Domestic",
        "deliveryPointValidation": "UNDELIVERABLE"
      }
    },
    {
      "address": {
        "addressLine1": "400 NW 65th St",
        "addressType": "DOMESTIC",
        "city": "Seattle",
        "countryName": "United States",
        "countryCodeIso3": "USA",
        "countyCode": "53033",
        "countyName": "King",
        "stateCode": "WA",
        "zipCode": "98117",
        "zipCodeSuffix": "5026"
      },
      "addressMetaData": {
        "confidenceScore": 100.0,
        "addressType": "Domestic",
        "deliveryPointValidation": "CONFIRMED",
        "residentialDeliveryIndicator": "RESIDENTIAL"
      }
    },
    {
      "address": {
        "addressLine1": "400 NE 65th St",
        "addressType": "DOMESTIC",
        "city": "Seattle",
        "countryName": "United States",
        "countryCodeIso3": "USA",
        "countyCode": "53033",
        "countyName": "King",
        "stateCode": "WA",
        "zipCode": "98115",
        "zipCodeSuffix": "6463"
      },
      "addressMetaData": {
        "confidenceScore": 98.0,
        "addressType": "Domestic",
        "deliveryPointValidation": "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER",
        "residentialDeliveryIndicator": "RESIDENTIAL"
      }
    }
  ],
  "validationKey": -2009470897
}
```

We only show the user the CONFIRMED address, the second address that came back from the API, but when they select that address what actually gets sent to the update endpoint is the first address that came back from the API.

### PR DESCRIPTION
**Pull request by erikphansen**
## Description
This PR addresses two issues:
- resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/4328: prevent the FE from sending a "bad" suggested address to the update endpoint
- resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/4264: reset the radio button state each time the validation modal opens.
- should also resolve https://github.com/department-of-veterans-affairs/va.gov-team/issues/4327: the second time you try to force through a "bad" user-entered address the update fails

## Testing done
Local

## Screenshots
N/A

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

File: src/platform/user/profile/vet360/actions/transactions.js [hunk 1]
```diff
@@ -233,7 +241,7 @@ export const validateAddress = (
         type: ADDRESS_VALIDATION_CONFIRM,
         addressFromUser: userEnteredAddress.address, // need to use the address with iso3 code added to it
         addressValidationType: fieldName,
-        selectedAddress: suggestedAddresses[0], // always select the first address as the default
+        selectedAddress: confirmedSuggestions[0], // always select the first address as the default
```
Comment (erikphansen) [inline src/platform/user/profile/vet360/actions/transactions.js]: By default we need to select the first of the _confirmed_ addresses we got from the API. The bug was that we were passing the first overall suggestion, which in some cases could have been a bad address. And if the user just accepted that default selection we'd send a bad address to the update endpoint. Also, this led to an issue where the UI would show a selected address that didn't match the data in Redux. 😱

File: src/platform/user/profile/vet360/util/local-vet360.js [hunk 2]
```diff
@@ -382,26 +382,6 @@ export default {
               residentialDeliveryIndicator: 'RESIDENTIAL',
             },
           },
-          {
```
Comment (erikphansen) [inline src/platform/user/profile/vet360/util/local-vet360.js]: Updated this response to match exactly what we get from the real API

File: src/platform/user/profile/vet360/reducers/index.js [hunk 3]
```diff
@@ -213,6 +213,7 @@ export default function vet360(state = initialState, action) {
           suggestedAddresses: action.suggestedAddresses,
           validationKey: action.validationKey,
           selectedAddress: action.selectedAddress,
+          selectedAddressId: '0',
```
Comment (erikphansen) [inline src/platform/user/profile/vet360/reducers/index.js]: Gotta "reset" the `selectedAddressId` each time the validation modal opens.

**Review by ncksllvn — APPROVED** [review]

**Review by rianfowler — APPROVED** [review]
