### PR TITLE
GIBCT profile fixes (OPE code, for profit school -> institution, cautionary info)

### LINKED ISSUE #5294: GI Bill CT: Displaying incorrect OPE code
The staging version of the tool is showing an incorrect OPE code in the "Additional information section".

The tool should be displaying the 8-digit OPE code, however it is currently showing a messed up version of the 6-digit OPE code. Unfortunately for all of us, many OPE codes start with zeros and those tend to be stripped somewhere along the data pipeline.

image

@mphprogrammer @saneshark @leannammiller

### PR DESCRIPTION
**Pull request by U-DON**
### Changes
* Display facility, IPEDS, and OPES codes as they are without converting to numbers in order to preserve leading zeros. Resolves #5294.
    > screen shot 2017-04-12 at 9 32 54 pm

* Display "For profit school" and "[school type] institution" for any other school type. Resolves department-of-veterans-affairs/vets.gov-team#2082.
    > screen shot 2017-04-12 at 9 28 25 pm

* Hide table as well and the list (in smaller or mobile view) and disclaimer when there are zero student complaints. Hide any rows that have 0 complaints (screenshot in change below). Resolves department-of-veterans-affairs/vets.gov-team#2097.
    > screen shot 2017-04-12 at 9 27 18 pm

* Changed "Student Complaints" to "Total Complaints" and bolded the row. Resolves department-of-veterans-affairs/vets.gov-team#2118.
    > screen shot 2017-04-12 at 9 28 03 pm

### CODE REVIEW

File: src/js/gi/components/profile/CautionaryInformation.jsx [hunk 1]
```diff
@@ -74,75 +83,60 @@ export class CautionaryInformation extends React.Component {
...
-          {complaints.map((c) =>
-            <ListRow key={c.description} description={c.description} value={c.thisCampus}/>)}
-          <div className="row">
-            <div className="small-11 columns">
-              <p><strong>Total complaints:</strong></p>
-            </div>
-            <div className="small-1 columns">
-              <p className="number"><strong>{it.complaints.facilityCode}</strong></p>
-            </div>
+        {it.complaints.mainCampusRollUp && (<div>
```
Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: Hide everything (table, list, disclaimer) if there are 0 total complaints.

File: src/js/gi/components/profile/CautionaryInformation.jsx [hunk 2]
```diff
@@ -74,75 +83,60 @@ export class CautionaryInformation extends React.Component {
         <div className="student-complaints">
           <div className="link-header">
             <h3>
-              {it.complaints.mainCampusRollUp}&nbsp;
-              <a href="http://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#complaints" target="_blank">student complaints</a>
+              {+it.complaints.mainCampusRollUp}&nbsp;
```
Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: Apparently can come in as `null`, so have to do the numeric conversion here.

File: src/js/gi/components/profile/CautionaryInformation.jsx [hunk 3]
```diff
@@ -74,75 +83,60 @@ export class CautionaryInformation extends React.Component {
...
-                    thisCampus={c.thisCampus} allCampuses={c.allCampuses}/>)}
-            </tbody>
-          </table>
-        </div>
-
-        <div className="list">
-          <h4>This campus</h4>
-          {complaints.map((c) =>
-            <ListRow key={c.description} description={c.description} value={c.thisCampus}/>)}
-          <div className="row">
```
Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: This row for "This campus" and the corresponding one for "All campuses" in the mobile list view were duplicates of the "Student complaints" (now correctly labeled as "Total complaints") rows. So these were removed.

**Comment by saintsoup52** [comment]
Thank you for doing this... unfortunately we are still showing the wrong OPE ID. We should be showing the 8-digit ID number not the OPE 6 one.

**Comment by U-DON** [comment]
Just updated to using 8 digit OPE code instead of 6. Had already resolved the trimming of leading zeros, so this just a matter of referencing the correct attribute.

File: src/js/gi/components/profile/CautionaryInformation.jsx [hunk 4]
```diff
@@ -1,43 +1,52 @@
 import React from 'react';
-import { connect } from 'react-redux';
-import { showModal } from '../../actions';
+
 import AlertBox from '../../../common/components/AlertBox';
 
 const TableRow = ({ description, thisCampus, allCampuses }) => {
+  if (!thisCampus && !allCampuses) return null;
```
Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: `TableRow` reports the same data as `ListRow`, but the table splits the number of complaints into two columns; complaints for this campus and complaints for all campuses. So just hiding the row if both are zero.

File: src/js/gi/components/profile/CautionaryInformation.jsx (hunk 1 above)
Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: Unless otherwise commented, most of this block of changes is just indenting everything that's displayed only after passing this condition.

File: src/js/gi/components/profile/AdditionalInformation.jsx [hunk 5]
```diff
@@ -125,21 +125,21 @@ export class AdditionalInformation extends React.Component {
...
-              {+it.cross === 0 ? 'N/A' : +it.cross}
+              {it.cross || 'N/A'}
             </p>
             <p>
               <strong>
                 <a onClick={this.props.onShowModal.bind(this, 'opeCode')}>ED OPE code:</a>
                 &nbsp;
               </strong>
-              {+it.ope6 === 0 ? 'N/A' : +it.ope6}
+              {it.ope || 'N/A'}
```
Comment (annekainicUSDS) [inline src/js/gi/components/profile/AdditionalInformation.jsx]: Did you mean for this to be `ope` instead of `ope6`?

File: src/js/gi/components/profile/CautionaryInformation.jsx [hunk 6]
```diff
@@ -1,43 +1,52 @@
...
+  const bold = description === 'Total Complaints';
   return (
     <tr>
-      <th><strong>{description}</strong></th>
-      <td className="number">{thisCampus}</td>
-      <td className="number">{allCampuses}</td>
+      <th><b>{description}</b></th>
```
Comment (annekainicUSDS) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: Is there a reason you're switching from the `<strong>` tag to `<b>`? Generally I prefer using `<strong>` so that it conveys mean to screen readers.

File: src/js/gi/components/profile/HeadingSummary.jsx [hunk 7]
```diff
@@ -12,6 +12,7 @@ class HeadingSummary extends React.Component {
 
   render() {
     const it = this.props.institution;
+    it.type = it.type && it.type.toLowerCase();
```
Comment (annekainicUSDS) [inline src/js/gi/components/profile/HeadingSummary.jsx]: Confirming we're checking this because it's possible to not have a `it.type`?

**Review by annekainicUSDS — COMMENTED** [review]
Couple of minor comments. Also, tried testing this locally, but for some reason search results weren't working for me. Wanted to make sure that the totals were being added correctly (it looks like from the screenshot in the description that the total should be 2 not 1?)

File: src/js/gi/components/profile/HeadingSummary.jsx (hunk 7 above)
Comment (U-DON) [inline src/js/gi/components/profile/HeadingSummary.jsx]: The data we get can be a bit patchy and have `null` for various values. In general, I doubt we'll have an issue of a `null` type, but this is just to ensure there's no error here.

File: src/js/gi/components/profile/AdditionalInformation.jsx (hunk 5 above)
Comment (U-DON) [inline src/js/gi/components/profile/AdditionalInformation.jsx]: Yup, we were incorrectly using the 6-digit value (`ope6`) when we should've been using the full 8-digit value (`ope`).

File: src/js/gi/components/profile/CautionaryInformation.jsx (hunk 6 above)
Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: I chose `<b>` here since it's not really used for emphasis relative to its surrounding elements. I think of `<strong>` being used in a phrase or sentence.

Comment (U-DON) [inline src/js/gi/components/profile/CautionaryInformation.jsx]: Although, it does help this row separate itself from the other rows, so I think I'll change it back to `<strong>`.

**Comment by U-DON** [comment]
To test locally, you'd need to set up GIDS as well, but I haven't gotten around to that myself. Instead, I modified `config.js` to point to the dev API (`url: 'https://dev-api.vets.gov/v0/gi'`).

The totals thing is a bit weird, but complaints can apparently have multiple types. So in that case, it probably means that there was one complaint that fit those two categories.

File: src/js/gi/components/profile/AdditionalInformation.jsx (hunk 5 above)
Comment (annekainicUSDS) [inline src/js/gi/components/profile/AdditionalInformation.jsx]: Ah okay, just wanted to make sure!

**Comment by annekainicUSDS** [comment]
@U-DON thanks for the responses! Everything LGTM now

**Review by annekainicUSDS — APPROVED** [review]
