### PR TITLE
set force auth to true after login

### LINKED ISSUE #9184: avoid SSOe auto login loops
SSOe auto login works by testing for a user session on VA.gov and on SSOe, and if the states differ making a request to the API to login.

There are a few scenarios in which a user will be logged into SSOe, but fail to log into VA.gov.  In this case we need to prevent auto login from happening after the first attempt to avoid an infinite loop.

One such scenario, outlined as [error case 5 in the SSOe product guide](https://docs.google.com/document/d/1gG6Ph1xvAYJ9Ith6RA5_F7i-ujYECX0U6j_NfQx-T-U/edit), is when a user signs in and their account has been flagged with suspicious activity.  In this case, SSOe will not redirect the user back to VA.gov, but instead just leave them on the IAM portal in a logged in state.  The inability to redirect back to VA.gov means that we will never be able to establish a session for that user, meanwhile their SSOe session status will always come back as "active".

### PR DESCRIPTION
**Pull request by ericbuckley**
Setting `?force=true` in the query parameter before issuing an SSOe authentication request
will indicate to SSOe that the user has to re-enter their credentials, even if they already have an active SSOe session.

This PR updates the local storage variable in 3 places to guarantee that the next authentication request will use for force parameter.  
  1) after a manual login
  2) after an auto login
  3) after we've detected that inbound ssoe is disabled

This will prevent the user from getting into any auto login loops between va.gov and eauth.va.gov.

closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/9184

### CODE REVIEW

File: src/platform/user/authentication/utilities.js [hunk 1]
```diff
@@ -15,6 +16,11 @@ export const ssoKeepAliveEndpoint = () => {
   return `https://${envPrefix}eauth.va.gov/keepalive`;
 };
 
+function inboundSSOe() {
+  // TODO: check to see if inbound ssoe is enabled
```
Comment (hinzed1127) [inline src/platform/user/authentication/utilities.js:20]: unfortunately this is gonna require accessing the redux store where all the feature flags live right now, which has 2 options I'm not crazy about:

1. import the redux store and [access it directly](https://redux.js.org/api/store#getstate). right now the store is initialized in `src/platform/startup/index.js` and isn't exported, so I'm having a hard time seeing a clean way to do that w/ minimal changes
2. add another argument with the flag and pass in the feature flag from a connected component that's calling login. that's probably easier right now, but `sessionTypeUrl is already getting nasty with the amount of arguments it's taking.

if route 2 seems to be the best option, then maybe changing `sessionTypeUrl` accept an object as an argument and destructure it to be more legible, eg

```js
sessionTypeUrl({ type = '', version = 'v0', application, to, queryParams = {}, inboundSSOe}){
 // ....
}
```
I'm not crazy about either, but with the redux store as the source of truth, not sure if there's a way around the messiness

File: src/platform/user/authentication/utilities.js [hunk 2]
```diff
@@ -105,16 +113,16 @@ function redirect(redirectUrl, clickedEvent) {
...
-    'login-link-clicked-modal',
-  );
+  const url = loginUrl(policy, version, application, to);
+  setForceAuth();
+  return redirect(url, 'login-link-clicked-modal');
 }
 
 export function autoLogin() {
   const url = sessionTypeUrl('idme', 'v1', undefined, undefined, {
     inbound: 'true',
```
Comment (hinzed1127) [inline src/platform/user/authentication/utilities.js:123]: what's the logic that `vets-api` is applying based on this param? anything that would affect subsequent client-side interactions?

File: src/platform/user/authentication/utilities.js [hunk 3]
```diff
@@ -105,16 +113,16 @@ function redirect(redirectUrl, clickedEvent) {
...
   });
+  setForceAuth();
```
Comment (hinzed1127) [inline src/platform/user/authentication/utilities.js:125]: is this only going to force someone to enter credentials if there's an error state? I.e., I get redirected to autologin, and am only prompted to log in again if something fails?

**Comment by hinzed1127** [comment]
So if I understand this correctly, adding force auth will require the user to enter their credentials again. Does this guarantee that they won't still end up in an incongruous state somehow where we incorrectly see a false positive IAM session and attempt inbound? I guess I'm failing to see how this 100% safeguards against a redirect loop

File: src/platform/user/authentication/utilities.js (hunk 2 above)
Comment (ericbuckley) [reply src/platform/user/authentication/utilities.js:123]: if login fails for any reason, and the `?inbound=true` query parameter was specified, then the response will contain `?auth=force-needed` rather than `?auth=fail`.  On the FE side we just ignore the former and return the user to where they left off rather than displaying the failure page.

File: src/platform/user/authentication/utilities.js (hunk 3 above)
Comment (ericbuckley) [reply src/platform/user/authentication/utilities.js:125]: yeah.  The idea is that we'll allow SSOe to short circuit the request and return whatever SAML response they have cached once.  If it works, great the user is logged in.  However, if it fails for any reason, any subsequent attempt to login should have the `?force=true` query parameter set, meaning the user should be forced to reenter their credentials.

**Comment by ericbuckley** [comment]
> So if I understand this correctly, adding force auth will require the user to enter their credentials again. Does this guarantee that they won't still end up in an incongruous state somehow where we incorrectly see a false positive IAM session and attempt inbound? I guess I'm failing to see how this 100% safeguards against a redirect loop

[auto login will only happen if force auth is not set](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/sso/index.js#L37-L39).  By setting this value right after we attempt a login (manual or auto), we guarantee that we will only try this once and not get stuck in a loop.

File: src/platform/user/authentication/utilities.js (hunk 1 above)
Comment (ericbuckley) [reply src/platform/user/authentication/utilities.js]: @hinzed1127 I think I found another way around this.  In the AutoSSO container I've added a condition to `setForceAuth` if inbound is disabled, that way we don't need to run that check in the utilities function.  Could you take another look?

**Review by hinzed1127 — APPROVED** [review]
I think this is ready for a larger review now

File: src/platform/site-wide/user-nav/tests/containers/AutoSSO.unit.spec.jsx [hunk 4]
```diff
@@ -20,51 +20,6 @@ describe('<AutoSSO>', () => {
     };
   });
 
-  it('should not call setForceAuth if auth query param is set to "success"', () => {
```
Comment (cvalarida) [inline src/platform/site-wide/user-nav/tests/containers/AutoSSO.unit.spec.jsx:23]: Should the `!useInboundSSOe` bit be tested instead?

File: src/platform/user/authentication/utilities.js [hunk 5]
```diff
@@ -126,13 +117,9 @@ export function verify(version = 'v0') {
   return redirect(sessionTypeUrl('verify', version), 'verify-link-clicked');
 }
 
-export function logout(version = 'v0') {
+export function logout(version = 'v0', clickedEvent = 'logout-link-clicked') {
```
Comment (cvalarida) [inline src/platform/user/authentication/utilities.js:120]: It doesn't look like this new parameter is tested for, right?

**Review by cvalarida — APPROVED** [review]
I don't really understand the changes made here, but I trust @hinzed1127 can review for that context. I'm mostly thinking about the test coverage. Looks like it could use a couple more tests.

File: src/platform/site-wide/user-nav/tests/containers/AutoSSO.unit.spec.jsx (hunk 4 above)
Comment (ericbuckley) [reply src/platform/site-wide/user-nav/tests/containers/AutoSSO.unit.spec.jsx:23]: yeah, I'll add a couple of tests

File: src/platform/user/authentication/utilities.js (hunk 5 above)
Comment (ericbuckley) [reply src/platform/user/authentication/utilities.js:120]: ill add a couple of tests
