### PR TITLE
Disables List view on mobile and fixes it for small screens

### LINKED ISSUE #4427: Hide list / card toggler on small screens [Was: Prescription list view needs labels]
When toggling into list view, the table header labels disappear. Each cell loses its label.

screen shot 2016-12-16 at 6 03 00 pm

Related to #4411

### PR DESCRIPTION
**Pull request by bshyong**
Resolves #4427 by disabling the toggle to List view on mobile devices and dynamically switching to card view on small screens for desktop

### CODE REVIEW

**Comment by U-DON** [comment]
I think the decision was to always use card view in mobile and that the toggle should only be available on desktop. I left a suggestion (that may or may not work) in the issue.

**Comment by bshyong** [comment]
@U-DON The implementation in this PR works in the following way:
- View state is always set to 'card' by default
- On mobile devices, the toggle is not rendered so users cannot switch to list view on mobile
- On desktop, if a user toggles to list view and then resizes the screen to less than 600px in width, they will end up with the buggy view. To address this, we can either add the labels in css (implemented here), or add a [debounced] event listener on `windowresize` so automatically change the view state back to 'card' if the window is resized

We can only make a pure CSS solution if we render both views and selectively hide one by setting `display: none`—I think that doing this places unnecessary load on the client because they have to render duplicated information

**Comment by bshyong** [comment]
Screenshot of labels for small screen desktop. Looking back at this, it might be cleaner from a UX/Design perspective to just listen to window resize events and change the state to card view. Unless you are opposed to that approach, I'll implement that so we can get rid of the list view for good on desktop screens < 600px wide

screen shot 2016-12-19 at 10 37 52 am

**Comment by U-DON** [comment]
I agree on the drawback of a pure CSS solution (unnecessary operations to render card view just to hide it), so we don't have to do it that way. I'm down with the resize event implementation.

On a related note, I'm not sure if I'm remembering incorrectly, but I thought list view was intended to be the default so that users don't get confused by the two-column card view. Maybe @gnakm can give the final word on that.

**Comment by bshyong** [comment]
@gnakm summarizing for clarity

1. Is the List view the default view on desktop?
2. List view will be completely disabled on mobile devices: only the card view will be shown
3. On desktop, it is possible for the user to resize their window to < 600 px which breaks the List view. In this case, we will automatically toggle to card view if resized, and disable the toggle switch.

Please add notes if you have thoughts on any of the above!

**Comment by gnakm** [comment]
@bshyong @U-DON 

Here are my thoughts. 
I think default should be cards on desktop. It is very important for us to have a list _option_ for those with limited mobility and head trauma (some users we talked to and did testing with). I've been helping the core team with visual consistency throughout Vets.gov and a lot of things are defaulted as cards so we should stick to that. Also, reading from above, the responsiveness of switching defaults certainly doesn't sound ideal. With that said, I think we should be conscientious of Veteran feedback around both views and the option to toggle.

**Comment by bshyong** [comment]
The above feedback has been implemented:
- Default view style remains as `card`.
- Mobile devices will only ever see the `card` view, with no toggle to switch to the list view
- Desktop browsers will see a toggle that allows switching to `list` view
- Desktop browsers that resize their screen to < 600 px will see the `card` view and the toggle will be hidden

**Comment by U-DON** [comment]
LGTM.

File: src/js/rx/containers/Active.jsx [hunk 1]
```diff
@@ -22,6 +24,15 @@ class Active extends React.Component {
   constructor(props) {
     super(props);
     this.handleSort = this.handleSort.bind(this);
+
+    this.checkWindowSize = _.debounce(() => {
+      if (document.documentElement.clientWidth < 600) {
```
Comment (U-DON) [inline src/js/rx/containers/Active.jsx]: How did you determine it was 600? Should it be assigned to a constant so it's clear what this limit is for?

Comment (bshyong) [inline src/js/rx/containers/Active.jsx]: Should we put a comment here? It is 600 because the `$small` breakpoint from foundation is set at `40em`, and our base font-size is 15px

Comment (bshyong) [inline src/js/rx/containers/Active.jsx]: I just thought of another way to do this. We could assign an ID to the view toggle element and then instead of checking window width, check if that element is visible in the DOM. The view toggle element should be hidden automatically by CSS classes (`display:none`)

Comment (U-DON) [inline src/js/rx/containers/Active.jsx]: Sure, I'm on board with that. Could potentially use a React ref as well.

File: src/js/rx/containers/Active.jsx [hunk 2]
```diff
@@ -65,7 +68,7 @@ class Active extends React.Component {
     ];
 
     return (
-      <div className="rx-view-toggle">View:&nbsp;
+      <div className="rx-view-toggle" ref="viewToggle">View:&nbsp;
```
Comment (U-DON) [inline src/js/rx/containers/Active.jsx]: Although this is easier to work with, I've generally been trying to follow React's guidelines of using the callback version of refs.

I guess I don't mind either way, but thoughts on following their recommendation in case they deprecate the old way of using refs?

> If you are currently using `this.refs.myRefName` to access refs, we recommend using this pattern instead.

https://facebook.github.io/react/docs/refs-and-the-dom.html

File: src/js/rx/containers/Active.jsx [hunk 3]
```diff
@@ -26,7 +26,10 @@ class Active extends React.Component {
     this.handleSort = this.handleSort.bind(this);
 
     this.checkWindowSize = _.debounce(() => {
-      if (document.documentElement.clientWidth < 600) {
+      const viewToggleElement = this.refs.viewToggle;
```
Comment (U-DON) [inline src/js/rx/containers/Active.jsx]: What's happening here might not be obvious to someone unfamiliar with the behavior, so might be helpful to leave a comment about how the stylesheet is hiding the button when the window's resized to a small screen.

**Comment by bshyong** [comment]
Great I'll add the comment now and get it merged!

--
Ben Shyong
408-505-9891




On Tue, Dec 20, 2016 at 9:03 AM -0800, "Eugene Doan" <notifications@github.com> wrote:












@U-DON commented on this pull request.





In src/js/rx/containers/Active.jsx:
> @@ -65,7 +68,7 @@ class Active extends React.Component {
     ];
 
     return (
-      <div className="rx-view-toggle">View:&nbsp;
+      <div className="rx-view-toggle" ref="viewToggle">View:&nbsp;



Although this is easier to work with, I've generally been trying to follow React's guidelines of using the callback version of refs.


I guess I don't mind either way, but thoughts on following their recommendation in case they deprecate the old way of using refs?



If you are currently using this.refs.myRefName to access refs, we recommend using this pattern instead.



https://facebook.github.io/react/docs/refs-and-the-dom.html





In src/js/rx/containers/Active.jsx:
> @@ -26,7 +26,10 @@ class Active extends React.Component {
     this.handleSort = this.handleSort.bind(this);
 
     this.checkWindowSize = _.debounce(() => {
-      if (document.documentElement.clientWidth < 600) {
+      const viewToggleElement = this.refs.viewToggle;



What's happening here might not be obvious to someone unfamiliar with the behavior, so might be helpful to leave a comment about how the stylesheet is hiding the button when the window's resized to a small screen.
