### PR TITLE
about this request aria label

### LINKED ISSUE #109488: [a11y-defect-2]: Screen reader: Evidence request links must include visible text in accessible labels
### Point of contact

@1copenut

### Severity level

2, Serious. Should be fixed in 1-2 sprints post-launch.

### Details

While auditing the First-party evidence request claims, I noticed the "About this request" links sometimes read out different text. I determined the accessible `aria-label` was different than the visible label, so screen readers were announcing the accessible label and voice controls would not click the link without zooming into a grid instead of saying "Click about this request" and selecting a number. Screenshot attached.

---

Image

### Reproduction steps

1. Log into staging, using a test user who has new first and third-party evidence requests. I tested with 211.
2. Go to `/track-claims/your-claims` after logging in
3. Click on a claim, then click on the **Files** tab
4. Turn on the screen reader of your choice
5. Tab or arrow to the nearest "About this request link"
6. Verify it reads out text that does not include "about this request" in the announcement

### Proposed solution or next steps

Adjust the rendered markup to include the visible text in the accessible label:

```diff
<a
- aria-label="Details for PTSD - Need stressor details/med evid personal trauma incdnt"
+ aria-label="About this request for details for PTSD - Need stressor details/med evid personal trauma incdnt"
- title="Details for PTSD - Need stressor details/med evid personal trauma incdnt"
  class="vads-c-action-link--blue"
  href="/track-claims/your-claims/600614029/needed-from-you/554707"
>About this request</a>
```

### References, articles, or WCAG support

1. [Understanding SC 2.5.3: Label in name (Level A)](https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html)

### Type of issue

- [ ] Axe-core
- [x] Screenreader | assistive tech & device support
- [ ] Keyboard
- [x] Voice command
- [ ] Zoom
- [ ] Color, typography, & visual elements
- [ ] Components and pattern standards
- [ ] Content organization
- [ ] Focus
- [ ] Headings
- [ ] Content style guide
- [ ] Link and button labels
- [ ] Semantic HTML
- [ ] Markup and metadata
- [ ] Non-text content and media
- [ ] Overall user experience
- [ ] Cognitive | user flows & navigating
- [ ] URL standards
- [ ] Something else

### PR DESCRIPTION
**Pull request by janechodance**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

Adjust about this request link aria label

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/109488

## Testing done

testing locally

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |     
Screenshot 2025-05-13 at 10 26 42 AM
  |

## What areas of the site does it impact?

CST evidence request

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

File: src/applications/claims-status/components/claim-files-tab/FilesNeeded.jsx [hunk 1]
```diff
@@ -79,8 +79,18 @@ export default function FilesNeeded({ item, previousPage = null }) {
       <span className="alert-description">{getItemDescription()}</span>
       <div className="link-action-container">
         <Link
-          aria-label={`Details for ${item.displayName}`}
-          title={`Details for ${item.displayName}`}
+          aria-label={
+            cstFriendlyEvidenceRequests
+              ? `About this request for ${item.friendlyName ||
```
Comment (dysbo) [inline src/applications/claims-status/components/claim-files-tab/FilesNeeded.jsx:84]: can we just define this once and use it twice?

Comment (1Copenut) [reply src/applications/claims-status/components/claim-files-tab/FilesNeeded.jsx:84]: Following on @dysbo with accessibility testing results. The change works perfectly in NVDA (Chrome & Firefox), Narrator on Edge, and MS Voice Access. I was able to see the accessible labels and control them from Links menus and by voice command.

**Review by 1Copenut — DISMISSED** [review]
💯 for accessibility

**Review by dysbo — APPROVED** [review]
