### PR TITLE
Fix staff profile sidenav

### LINKED ISSUE #17132: Staff Profile pages are different on Staging and Prod
## Issue description
Pittsburgh staff profile pages are different on staging compared to production. this can be problematic from testing perspective. It's challenging to know what expected behavior is when the environments are different. 

**Causes an issue in Tugboat/review environments which impact roll-outs and new editors**

**The correct behavior is on Prod**

Example:  https://staging.va.gov/pittsburgh-health-care/staff-profiles/alan-petrazzi/

<details>
<summary> Sidenav is present on Prod </summary>

image

</details>
---
<details>
<summary> Sidenav is missing on Staging </summary>

image

</details>

There's also a Javascript error on the page: 

```
helpers.js?c526:139 Uncaught TypeError: Cannot read property 'filter' of undefined
    at normalizeSideNavData (helpers.js?c526:139)
```

NOTE: Whether or not Side Nav is expected is not within scope of this issue. 

## Tasks
- [x] Understand the reason staging and production are different - what environment checks are in play?

### PR DESCRIPTION
**Pull request by mpelzsherman**
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/17132

### CODE REVIEW

**Review by brangi — APPROVED** [review]

File: src/platform/site-wide/side-nav/helpers.js [hunk 1]
```diff
@@ -136,7 +136,7 @@ export const normalizeSideNavData = data => {
   const items = data?.links;
 
   // Derive only nav items that are relevant for the current page.
-  const relevantNavItems = items.filter(item =>
+  const relevantNavItems = items?.filter(item =>
```
Comment (kelsonic) [inline src/platform/site-wide/side-nav/helpers.js:139]: lgtm!

**Review by kelsonic — APPROVED** [review]

File: src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid [hunk 2]
```diff
@@ -6,113 +6,108 @@
     For an example of how to make a string look like this, look at in `src/site/layouts/person_profile.drupal.liquid` where sidebarData is being assigned.
 {% endcomment %}
 
-{% if buildtype != 'vagovprod' %}
-    <script nonce="**CSP_NONCE**" type="text/javascript">
-      window.sideNav = {{ sidebarData | json }};
-    </script>
```
Comment (mpelzsherman) [inline src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid:12]: All I really did here is remove the `if buildtype != 'vagovprod'` block, and auto-format the template.

**Review by jhonny218 — APPROVED** [review]
LGTM
