### PR TITLE
fix: heading for screen reader

### LINKED ISSUE #107718: [0781 PS] A11Y issue - Typo results in screen reader announcement error
See: https://github.com/department-of-veterans-affairs/va.gov-team/issues/107325#issuecomment-2806871520

[3.3] Upload 0781
Page: file-disability-claim-form-21-526ez/mental-health-form-0781/upload

### Issue: Typo results in screen reader announcement error

* **Page:** [Upload VA Form 21-0781](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/mental-health-form-0781/upload)  
* **Device:** Mac  
* **Orientation:** landscape  
* **Expected severity level:** 4  
* **Expected experience standard:** User encounters accurate, consistent content  
* **Description:** The top heading has a typo \- there’s a space between “21” and “-0781.” As a result, screen readers announce the “-” as a “minus” or a “negative.” For example, VoiceOver using Chrome announces “Upload VA Form 21 minus 0781.”  
* **How to recreate:** Access page  
* **Recommendation:** Remove the space between “21” and “-0781"

### PR DESCRIPTION
**Pull request by TranScripted**
## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Fixing the heading for manual page as the screen reader reads the "-" as a minus due to the space between "21" and "-0781". Removed the space.

closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/107718

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/107718

## Testing done
- ran test associated to page.
- used native macOS screen reader in chrome.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| manual Page Upload  |Screenshot 2025-10-06 at 3 03 16 PM|image|

## What areas of the site does it impact?

`manualPageUpload page`

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

File: src/applications/disability-benefits/all-claims/content/form0781/manualUploadPage.jsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import React from 'react';
 
-export const manualUploadPageTitle = 'Upload VA Form 21 -0781';
```
Comment (LinnJS) [inline src/applications/disability-benefits/all-claims/content/form0781/manualUploadPage.jsx:3]: Welp that was easy lol

**Review by LinnJS — APPROVED** [review]

**Review by freeheeling — APPROVED** [review]

**Review by RyanMunsch — APPROVED** [review]
