### PR TITLE
Fixes for news_story transformer

### LINKED ISSUE #13197: Missing href for news_story
## Issue Description
There is a missing href attribute

## Example:
```
<a class="vads-u-display--block vads-u-margin-bottom--7" href="/pittsburgh-health-care/stories" id="b7f11ebef38f0b0e20077d45e0ace8f9">See all stories</a>
<a class="vads-u-display--block vads-u-margin-bottom--7" href id="b7f11ebef38f0b0e20077d45e0ace8f9">See all stories</a>
```

## Example File
`/pittsburgh-health-care/stories/loss-is-common-human-experience/index.html`

## Tasks
- [ ] Figure out why there's a missing href.
- [ ] Resolve issue, and verify the output matches the GraphQL content build.

### PR DESCRIPTION
**Pull request by U-DON**
## Description

1. Fixed failing output schema validation for `news_story` by paring down the attributes expected from `fieldAuthor`.

2. Fixed missing `href` values in `news_story` pages. Fixes department-of-veterans-affairs/va.gov-team#13197.

    The `news_story.drupal.liquid` template was setting the value to `fieldListing.entity.entityUrl.path`, but the `news_story` transformer was not including `fieldListing` in the output.

## Testing done
Compared local builds. Ran transformer validation on the affected transformers.

## Acceptance criteria
- [ ] Links on `news_story` pages should have values for their `href` attributes.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

File: src/site/stages/build/process-cms-exports/schemas/output/node-news_story.js [hunk 1]
```diff
@@ -11,11 +11,31 @@ module.exports = {
...
+      type: 'object',
+      properties: {
+        entity: {
+          type: 'object',
+          properties: {
+            entityUrl: { $ref: 'EntityUrl' },
+          },
+        },
+      },
+    },
```
Comment (U-DON) [inline src/site/stages/build/process-cms-exports/schemas/output/node-news_story.js:38]: I would've used `usePartialSchema`, but then it would've formed a circular dependency with the `node-story_listing` output schema.

File: src/site/stages/build/process-cms-exports/schemas/output/node-news_story.js [hunk 2]
```diff
@@ -11,11 +11,31 @@ module.exports = {
     entityMetatags: { $ref: 'MetaTags' },
     entityUrl: { $ref: 'EntityUrl' },
     fieldAuthor: {
-      oneOf: [{ $ref: 'output/node-person_profile' }, { type: 'null' }],
+      oneOf: [
+        {
+          type: 'object',
+          properties: {
+            title: { type: 'string' },
+            fieldDescription: { type: ['string', 'null'] },
```
Comment (U-DON) [inline src/site/stages/build/process-cms-exports/schemas/output/node-news_story.js:19]: All instances of `fieldAuthor` in the GraphQL pages only had these two fields.

File: src/site/stages/build/process-cms-exports/schemas/output/node-story_listing.js [hunk 3]
```diff
@@ -11,6 +11,7 @@ module.exports = {
     changed: { type: 'number' },
     entityPublished: { type: 'boolean' },
     entityMetatags: { $ref: 'MetaTags' },
+    entityUrl: { $ref: 'EntityUrl' },
```
Comment (jhonnyoddball) [inline src/site/stages/build/process-cms-exports/schemas/output/node-story_listing.js:14]: `entityUrl` should be injected in every transformer's output. I don't think it is necessary to add it here. Can you please verify this?

Comment (U-DON) [reply src/site/stages/build/process-cms-exports/schemas/output/node-story_listing.js]: Nope, this wasn't necessary. Removed.

**Review by jhonny218 — APPROVED** [review]
