### PR TITLE
[Messaging] Fixes for Thread view and draft forms. ThreadHeader unit tests.

### LINKED ISSUE #199: Duplicate subject line and delete link on drafts
From the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30) there's a duplicate subject line and delete link on drafts. 

> screen_shot_2016-11-28_at_2_48_55_pm

When drafts are not part of  a thread we can remove the top subject line area which would remove the delete button and look like this:

image

but if it's a draft to a thread it would look like this:

image

Also I removed the delete link at the top that would delete the message, I think at this view you should only be able to delete the draft not the entire message.

### PR DESCRIPTION
**Pull request by U-DON**
## Changes:
* Various style fixes.
    * Un-bolded "Attach" link in reply form.
    * Consistent font-size on buttons in Thread.
* Fixed delete draft behaviors.
    * Thread was replacing reply form with new message form after clearing draft.
    * Compose was handling undefined event argument.
* Hide title section for drafts of new messages. Hide delete button in title section on all drafts.
    * Closes department-of-veterans-affairs/messaging-fe#199.
* Unit tests for ThreadHeader.

### CODE REVIEW

File: src/js/messaging/reducers/messages.js [hunk 1]
```diff
@@ -52,17 +47,20 @@ export default function messages(state = initialState, action) {
...
       state.data.draft.attachments.splice(action.index, 1);
       return set('data.draft.attachments', state.data.draft.attachments, state);
 
     case FETCH_THREAD_MESSAGE_SUCCESS: {
-      const updatedMessage = assign(
-        action.message.data.attributes,
-        { attachments: action.message.included }
-      );
+      const updatedMessage = {
+        ...action.message.data.attributes,
```
Comment (bshyong) [inline src/js/messaging/reducers/messages.js]: 👍

**Review by bshyong — APPROVED** [review]
LGTM
